"""Generate float32 Goertzel and Hann constants for the STM32 build."""

from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parents[2]
TRACKER_OUTPUT = ROOT / "firmware" / "core" / "rdmr_tracker_tables.h"
TRIG_OUTPUT = ROOT / "firmware" / "core" / "rdmr_trig_values.h"


def _literal(value: np.float32) -> str:
    text = f"{float(value):.9g}"
    if "." not in text and "e" not in text:
        text += ".0"
    return text + "f"


def _array(name: str, values: np.ndarray) -> list[str]:
    lines = [f"static const float {name}[{values.size}] = {{"]
    for start in range(0, values.size, 6):
        chunk = ", ".join(_literal(value) for value in values[start : start + 6])
        suffix = "," if start + 6 < values.size else ""
        lines.append(f"    {chunk}{suffix}")
    lines.append("};")
    return lines


def main() -> None:
    two_pi = np.float32(2.0 * np.pi)
    indices = np.arange(201, dtype=np.float32)
    frequencies = np.float32(45.0) + np.float32(
        indices * np.float32(0.05)
    )
    coefficients = np.float32(
        np.float32(2.0)
        * np.cos(
            np.float32(
                np.float32(two_pi * frequencies) / np.float32(1000.0)
            )
        )
    )
    window_indices = np.arange(400, dtype=np.float32)
    window = np.float32(
        np.float32(0.5)
        - np.float32(
            np.float32(0.5)
            * np.cos(
                np.float32(
                    np.float32(two_pi * window_indices) / np.float32(399.0)
                )
            )
        )
    )

    lines = [
        "#ifndef RDMR_TRACKER_TABLES_H",
        "#define RDMR_TRACKER_TABLES_H",
        "",
        "/* Generated by simulation/golden_model/generate_tracker_tables.py. */",
        *_array("rdmr_tracker_coefficients", coefficients),
        "",
        *_array("rdmr_tracker_window", window),
        "",
        "#endif",
        "",
    ]
    TRACKER_OUTPUT.write_text(
        "\n".join(lines),
        encoding="utf-8",
        newline="\n",
    )

    trig_indices = np.arange(2049, dtype=np.float32)
    trig_values = np.float32(
        np.sin(
            np.float32(
                np.float32(two_pi * trig_indices) / np.float32(2048.0)
            )
        )
    )
    trig_lines = [
        "#ifndef RDMR_TRIG_VALUES_H",
        "#define RDMR_TRIG_VALUES_H",
        "",
        "/* Generated by simulation/golden_model/generate_tracker_tables.py. */",
        *_array("rdmr_sine_table", trig_values),
        "",
        "#endif",
        "",
    ]
    TRIG_OUTPUT.write_text(
        "\n".join(trig_lines),
        encoding="utf-8",
        newline="\n",
    )


if __name__ == "__main__":
    main()
